name: Backpacks
version: 1.1
main: me.darqy.backpacks.Backpacks
author: Darq_Alder
softdepend: [Lockette, Deadbolt]

description: Multiple, multi-world backpacks
commands:
  createpack:
    description: Creates a new backpack
    usage: /<command> (backpack) (player) (world)
    aliases: [cpack]
  backpack:
    description: Opens the player's backpack
    usage: /<command> (backpack)
    aliases: [pack]
  inspectpack:
    description: Opens a read-only version of a backpack
    usage: /<command> [player] (backpack) (world)
    aliases: [ipack]
  listpacks:
    description: Lists a player's backpacks in a given world
    usage: /<command> (world) (player)
    aliases: [lpacks]
  packutils:
    description: Various utilities to help manage your backpack
    usage: /<command> [action] (p:[backpack])
    aliases: [upack]
    
